/*
 * lws-minimal-http-client-post
 *
 * Written in 2010-2019 by Andy Green <andy@warmcat.com>
 *
 * This file is made available under the Creative Commons CC0 1.0
 * Universal Public Domain Dedication.
 *
 * This demonstrates the a minimal http client using lws and POST.
 *
 * It POSTs both form data and a file to the form at
 * https://libwebsockets.org/testserver/formtest and dumps
 * the html page received generated by the POST handler.
 */

#ifdef USE_LINGXIN_NET_LIB

#include "lingxin_http.h"
#include "lingxin_common.h"
#include <libwebsockets.h>
#include <signal.h>
#include <string.h>

static int interrupted, bad = 0, status, completed;
static struct lws *client_wsi;

typedef struct
{
  HttpConfig *config;
  RequestCallback callback;
  void *response;
  size_t body_len;
  size_t body_sent;
} HttpClient;

static int callback_http(struct lws *wsi, enum lws_callback_reasons reason,
                         void *user, void *in, size_t len)
{
  logPrintf("WebSocket callback_ws:%d", reason);
  HttpClient *client = (HttpClient *)user;

  char buf[LWS_PRE + 1024], *start = &buf[LWS_PRE],
                            *end = &buf[sizeof(buf) - 1];
  unsigned char *p = (unsigned char *)start;

  int n;
  unsigned char **curPos = (unsigned char **)in;
  unsigned char *endPos;
  switch (reason)
  {

  case LWS_CALLBACK_ESTABLISHED_CLIENT_HTTP:
    status = (int)lws_http_client_http_response(wsi);
    lwsl_user("Connected with server response: %d\n", status);
    break;

  case LWS_CALLBACK_HTTP_BODY:
    logPrintf("LWS_CALLBACK_HTTP_BODY: %s", in ? (char *)in : "(null)");
    break;
  /* because we are protocols[0] ... */
  case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
    logPrintf("CLIENT_CONNECTION_ERROR: %s", in ? (char *)in : "(null)");
    client_wsi = NULL;
    bad = 1;
    char buffer[256];                         // 增大 buffer 大小
    const char *headerKey = "x-auth-reason:"; // 自定义 header 名称
    int lenOfHeaderKey = strlen(headerKey);   // 动态计算 header 名称长度

    // 获取自定义 header 的长度
    int lenOfHeaderValue = lws_hdr_custom_length(wsi, headerKey, lenOfHeaderKey);
    if (lenOfHeaderValue < 0)
    {
      logPrintf("Can't find %s", headerKey);
    }
    else
    {
      // 拷贝自定义 header 的内容到 buffer
      int copyResult = lws_hdr_custom_copy(wsi, buffer, sizeof(buffer), headerKey, lenOfHeaderKey);
      if (copyResult < 0)
      {
        logPrintf("Custom header too long: %s", headerKey);
      }
      else
      {
        logPrintf("Custom header: %s", buffer);
      }
    }
    char *errorMessage = (char *)in;
    if (strlen(buffer) > 0)
    {
      errorMessage = buffer;
    }
    break;

  case LWS_CALLBACK_CLIENT_RECEIVE:
    logPrintf("LWS_CALLBACK_CLIENT_RECEIVE:  %s", in);

    break;

  case LWS_CALLBACK_CLOSED_CLIENT_HTTP:
    client_wsi = NULL;
    bad = status != 200;
    lws_cancel_service(lws_get_context(wsi)); /* abort poll wait */
    break;

  case LWS_CALLBACK_RECEIVE_CLIENT_HTTP:
    n = sizeof(buf) - LWS_PRE;
    logPrintf("LWS_CALLBACK_RECEIVE_CLIENT_HTTP: %d,  %s", n, in);
    if (lws_http_client_read(wsi, (char **)&p, &n) < 0)
      return -1;
    return 0; /* don't passthru */

  case LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ:
    logPrintf("LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ: %d,  %s", len, in);
    if (client->callback != NULL)
    {
      client->callback(in, len, client->response);
    }
    return 0; /* don't passthru */

  case LWS_CALLBACK_COMPLETED_CLIENT_HTTP:
    logPrintf("LWS_CALLBACK_COMPLETED_CLIENT_HTTP%s", (char *)in);
    client_wsi = NULL;
    bad = status != 200;
    lws_cancel_service(lws_get_context(wsi)); /* abort poll wait */
    break;

    /* ...callbacks related to generating the POST... */
  case LWS_CALLBACK_CLIENT_APPEND_HANDSHAKE_HEADER:
    endPos = (*curPos) + len;
    if (!client->config->headers)
    {
      logPrintf("callback_ws headers null");
      return -1;
    }
    if (!client->config->headers->app_id ||
        lws_add_http_header_by_name(
            wsi, (const unsigned char *)"app_id",
            (const unsigned char *)client->config->headers->app_id,
            strlen(client->config->headers->app_id), curPos, endPos))
    {
      logPrintf("Failed to add HTTP header: app_id");
      return -1;
    }
    if (!client->config->headers->sn ||
        lws_add_http_header_by_name(
            wsi, (const unsigned char *)"sn",
            (const unsigned char *)client->config->headers->sn,
            strlen(client->config->headers->sn), curPos, endPos))
    {
      logPrintf("Failed to add HTTP header: sn");
      return -1;
    }
    if (!client->config->headers->signature ||
        lws_add_http_header_by_name(
            wsi, (const unsigned char *)"signature",
            (const unsigned char *)client->config->headers->signature,
            strlen(client->config->headers->signature), curPos, endPos))
    {
      logPrintf("Failed to add HTTP header: signature");
      return -1;
    }

    if (!client->config->headers->timestamp ||
        lws_add_http_header_by_name(
            wsi, (const unsigned char *)"timestamp",
            (const unsigned char *)client->config->headers->timestamp,
            strlen(client->config->headers->timestamp), curPos, endPos))
    {
      logPrintf("Failed to add HTTP header: timestamp");
      return -1;
    }
    // 添加 Content-Type: application/json 头
    if (lws_add_http_header_by_name(wsi, (unsigned char *)"Content-Type",
                                    (unsigned char *)"application/json",
                                    strlen("application/json"), curPos,
                                    endPos))
    {
      logPrintf("Failed to add HTTP header: Content-Type");
      return -1;
    }

    if (lws_add_http_header_content_length(wsi, client->body_len, curPos,
                                           endPos))
    {
      logPrintf("Failed to add HTTP header: Content-Length");
      return -1;
    }

    logPrintf("callback_ws headers: app_id:%s, sn:%s, signature:%s, "
              "timestamp:%s",
              client->config->headers->app_id, client->config->headers->sn,
              client->config->headers->signature,
              client->config->headers->timestamp);

    // 告诉 lws 我们将要发送 body
    lws_client_http_body_pending(wsi, 1);
    lws_callback_on_writable(wsi);
    break;
  case LWS_CALLBACK_CLIENT_HTTP_WRITEABLE:
    if (lws_http_is_redirected_to_get(wsi))
      break;

    n = LWS_WRITE_HTTP;
    size_t remaining = client->body_len - client->body_sent;
    size_t to_send = remaining > (end - start) ? (end - start) : remaining;

    memcpy(start, client->config->post_data + client->body_sent, to_send);
    client->body_sent += to_send;
    logPrintf("LWS_CALLBACK_CLIENT_HTTP_WRITEABLE,%s", start);

    if (lws_write(wsi, (uint8_t *)start, to_send, (enum lws_write_protocol)n) !=
        to_send)
    {
      logPrintf("LWS_CALLBACK_CLIENT_HTTP_WRITEABLE,error");
      return 1;
    }

    if (client->body_sent == client->body_len)
    {
      lws_client_http_body_pending(wsi, 0);
      n = LWS_WRITE_HTTP_FINAL;
    }

    if (n != LWS_WRITE_HTTP_FINAL)
      lws_callback_on_writable(wsi);

    return 0;
    break;
  default:
    break;
  }

  return lws_callback_http_dummy(wsi, reason, user, in, len);
}

static const struct lws_protocols protocols[] = {
    {"http", callback_http, sizeof(HttpClient), 0, 0, NULL, 0},
    LWS_PROTOCOL_LIST_TERM};

static void sigint_handler(int sig) { interrupted = 1; }

static void customLogEmit(int level, const char *line)
{
  logPrintf("customLogEmit: %d, %s", level, line);
  // Do nothing, effectively disabling all logs
}

int http_post(HttpConfig *config, RequestCallback userCallback,
              void *userData)
{
  struct lws_context_creation_info contextCreateInfo;
  struct lws_client_connect_info clientConnectInfo;
  struct lws_context *context;
  const char *p;
  int n = 0;
  signal(SIGINT, sigint_handler);

  memset(&contextCreateInfo, 0,
         sizeof contextCreateInfo); /* otherwise uninitialized garbage */

  contextCreateInfo.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;
  contextCreateInfo.port =
      CONTEXT_PORT_NO_LISTEN; /* we do not run any server */
  contextCreateInfo.protocols = protocols;
  /*
   * since we know this lws context is only ever going to be used with
   * one client wsis / fds / sockets at a time, let lws know it doesn't
   * have to use the default allocations for fd tables up to ulimit -n.
   * It will just allocate for 1 internal and 1 (+ 1 http2 nwsi) that we
   * will use.
   */
  contextCreateInfo.fd_limit_per_thread = (unsigned int)(1 + 1 + 1);

  // lws_set_log_level(LLL_ERR | LLL_WARN | LLL_NOTICE | LLL_INFO | LLL_DEBUG,
  // customLogEmit);

  lws_set_log_level(LLL_ERR | LLL_WARN | LLL_NOTICE, customLogEmit);

  context = lws_create_context(&contextCreateInfo);
  if (!context)
  {
    logPrintf("lws init failed\n");
    return 1;
  }

  memset(&clientConnectInfo, 0,
         sizeof clientConnectInfo); /* otherwise uninitialized garbage */
  clientConnectInfo.context = context;
  clientConnectInfo.ssl_connection = 0;
  clientConnectInfo.address = config->host;
  clientConnectInfo.port = config->port;
  clientConnectInfo.path = config->path;
  clientConnectInfo.host = config->host;
  clientConnectInfo.method = "POST";
  clientConnectInfo.alpn = "http/1.1";

  clientConnectInfo.protocol = protocols[0].name;

  clientConnectInfo.pwsi = &client_wsi;
  clientConnectInfo.pwsi = &client_wsi;

  struct lws *wsi = lws_client_connect_via_info(&clientConnectInfo);

  HttpClient *client = (HttpClient *)calloc(1, sizeof(HttpClient));
  client->config = config;
  client->body_len = strlen(config->post_data);
  client->body_sent = 0;
  client->callback = userCallback;
  client->response = userData;
  clientConnectInfo.userdata = client; // Set client as userdata
  lws_set_wsi_user(wsi, client);

  while (n >= 0 && client_wsi && !interrupted)
    n = lws_service(context, 0);

  lws_context_destroy(context);
  logPrintf("Completed: %s\n", bad ? "failed" : "OK");

  return bad;
}

#endif // USE_LINGXIN_NET_LIB