#pragma once

//#define CONFIG_AUDIO_ONLY
#if CONFIG_AUD_INTF_SUPPORT_G722
#define CONFIG_USE_G722_CODEC 1
#elif CONFIG_AUD_INTF_SUPPORT_OPUS
#define CONFIG_USE_OPUS_CODEC 1
#else
//#define CONFIG_USE_G711U_CODEC
//#define CONFIG_USE_G711A_CODEC
#endif

//#define SPK_GAIN_MAX        (0X15)
#define SPK_VOLUME_LEVEL (11) //[0,10]

#define BANDWIDTH_ESTIMATE_MIN_BITRATE   (500000)
#define BANDWIDTH_ESTIMATE_MAX_BITRATE   (2000000)
#define BANDWIDTH_ESTIMATE_START_BITRATE (800000)


